application: enduring-signal-227804
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: mysite.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: mysite.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: mysite.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: mysite.wsgi.application
  secure: always

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK 
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
libraries:
- name: django
  version: 1.11
- name: pytz
  version: 2016.4
- name: ssl
  version: latest
- name: six
  version: latest

skip_files:
  - ^manage\.py$
  - ^README\.md$
  - ^install_deps$
  - ^requirements/.*\.txt$
  - ^sitepackages/dev.*
  - ^.*\.(egg|dist)-info/.*$

  # Defaults.
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
